# -*- coding: utf-8 -*-
"""KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRaRFlhyL5O-MnRynX5WV2Cm068mjiAX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive

drive.mount('/content/drive')

cd /content/drive/"My Drive"

df1 = pd.read_excel('Colab Notebooks/kmean.xlsx', sheet_name='ex7data2_X', header=None)
df1.head()

X = np.array(df1)

import random
init_centroids = random.sample(range(0, len(df1)), 3)
init_centroids

centroids = []
for i in init_centroids:
    centroids.append(df1.loc[i])
centroids

centroids = np.array(centroids)

centroids

def calc_distance(X1, X2):
    return(sum((X1 - X2)**2))**0.5

def findClosestCentroids(ic, X):
    assigned_centroid = []
    for i in X:
        distance=[]
        for j in ic:
            distance.append(calc_distance(i, j))
        assigned_centroid.append(np.argmin(distance))
    return assigned_centroid

get_centroids = findClosestCentroids(centroids, X)
get_centroids

def calc_centroids(clusters, X):
    new_centroids = []
    new_df = pd.concat([pd.DataFrame(X), pd.DataFrame(clusters, columns=['cluster'])],
                      axis=1)
    for c in set(new_df['cluster']):
        current_cluster = new_df[new_df['cluster'] == c][new_df.columns[:-1]]
        cluster_mean = current_cluster.mean(axis=0)
        new_centroids.append(cluster_mean)
    return new_centroids

#get_centroids = findClosestCentroids(centroids, X)

#new_df = pd.concat([pd.DataFrame(X), pd.DataFrame(get_centroids, columns=['cluster'])],axis=1)

for i in range(10):
    get_centroids = findClosestCentroids(centroids, X)
    centroids = calc_centroids(get_centroids, X)
    #print(centroids)
    plt.figure()
    plt.scatter(np.array(centroids)[:, 0], np.array(centroids)[:, 1], color='black')
    plt.scatter(X[:, 0], X[:, 1], alpha=0.1)
    plt.show()

#Dimensionality Reduction

import cv2
im = cv2.imread('Colab Notebooks/tom.jpg')
im

im.shape

im = (im/255).reshape(200*200, 3)

random_index = random.sample(range(0, len(im)), 10)

random_index

centroids = []
for i in random_index:
    centroids.append(im[i])
centroids = np.array(centroids)

im = np.array(im)

for i in range(20):
    get_centroids = findClosestCentroids(centroids, im)
    centroids = calc_centroids(get_centroids, im)

im_recovered = im.copy()
for i in range(len(im)):
    im_recovered[i] = centroids[get_centroids[i]]

im_recovered = im_recovered.reshape(200,200, 3)

im1 = cv2.imread('Colab Notebooks/tom.jpg')
import matplotlib.image as mpimg
fig,ax = plt.subplots(1,2)
ax[0].imshow(im1)
ax[1].imshow(im_recovered)

